### ISSUE TITLE
(Verdaccio) TypeError: Cannot read property 'old' of undefined

### ISSUE THREAD

**Issue by NetOperatorWibby** [silverwind/updates#19]
Full error is:

```error
TypeError: Cannot read property 'old' of undefined
    at Promise.all.then.dati (~/node_modules/updates/updates.js:216:38)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

I'm _pretty_ sure this is an issue with [Verdaccio](https://www.verdaccio.org), which is what I'm using for my self-hosted npm registry. I've run the update command in another project that doesn't use modules I'm self-hosting and `updates` has no problem.

**Comment by silverwind** [comment]
Can you post your package.json or list of dependencies where you get the error?

**Comment by NetOperatorWibby** [comment]
My apologies for the lateness. My registry is [here](https://npm.inc.sh). _I only have one public package on it and the dependencies I'm trying to update are private._

I updated to the latest version of `updates` and the issue remains.

**Comment by silverwind** [comment]
Looks like the issue is with authentication ([info](https://github.com/npm/registry/blob/master/docs/user/authentication.md#how-to-authenticate)):

```` bash
$ curl https://npm.inc.sh/@inc%2fgotql
{
  "error": "authorization required to access package @inc/gotql"
}
````

Do you store your auth token for that registry in a `.npmrc` file?

I probably need a dependencythat is able to parsing the token.

**Comment by silverwind** [comment]
Try with `6.3.0`, it should pick up your auth token with the new `--auth` option.

**Comment by silverwind** [comment]
Actually, try `7.0.0`, I decided to automatically authorize if a token is present.

**Comment by NetOperatorWibby** [comment]
Alright, I think we're getting closer. I now get this error:

```
Error: Not found
    at Promise.all.then.dati (~/node_modules/updates/updates.js:220:14)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

To answer your previous question, my credentials indeed are in my `.npmrc` file.

**Comment by NetOperatorWibby** [comment]
I'm gonna try to fix this as well.

**Comment by NetOperatorWibby** [comment]
I added the below lines into this block: https://github.com/silverwind/updates/blob/master/updates.js#L218

```
console.log("—————");
console.log(data);
console.log("—————");
```

I saw two of my modules (`@inc/gotql` and `@inc/logger`) and `{ error: 'Not found' }`.

**Comment by silverwind** [comment]
This might be a 404 not found, try:

````
curl -v -H "Authorization: Bearer <token>" https://npm.inc.sh/@inc%2fgotql
````

**Comment by silverwind** [comment]
Just to be clear: you're sourceing all your package from the `npm.inc.sh` registry, right? You do specify `-r https://npm.inc.sh` to use that registry?

**Comment by NetOperatorWibby** [comment]
Not all my packages, just a couple. Most are from npm proper. I don't specify anything to use the registry, I'll check out the other parameters.

**Comment by NetOperatorWibby** [comment]
Response from the cURL:

```bash
*   Trying 206.189.172.155...
* TCP_NODELAY set
* Connected to npm.inc.sh (206.189.172.155) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=inc.sh
*  start date: Feb  7 03:05:13 2019 GMT
*  expire date: May  8 03:05:13 2019 GMT
*  subjectAltName: host "npm.inc.sh" matched cert's "npm.inc.sh"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fd9de009400)
> GET /@inc%2fgotql HTTP/2
> Host: npm.inc.sh
> User-Agent: curl/7.54.0
> Accept: */*
> Authorization: Bearer TOP_SECRET=
>
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200
< server: nginx/1.10.3 (Ubuntu)
< date: Mon, 11 Feb 2019 17:29:24 GMT
< content-type: application/json; charset=utf-8
< content-length: 16199
< x-powered-by: verdaccio/3.10.2
< access-control-allow-origin: *
< etag: "f424da80405e4b7c976041cde12c4534"
< vary: Accept-Encoding
< x-status-cat: http://flic.kr/p/aVuVsF
< strict-transport-security: max-age=31536000; includeSubdomains;
<
{
  "name": "@inc/gotql",
  "versions": {
    "1.4.0": {
      "author": {
        "name": "Paul Anthony Webb",
        "email": "paul@inc.sh"
      },
      "bugs": {
        "url": "https://hub.socii.network/inc"
      },
      "dependencies": {
        "got": "^9.5.0",
        "prepend-http": "^2.0.0"
      },
      "description": "A GraphQL query framework for server-side apps",
      "devDependencies": {
        "@inc/eslint-config": "^1.1.2",
        "ava": "^1.0.1",
        "eslint": "^5.12.0",
        "husky": "^1.3.1",
        "npm-run-all": "^4.1.5",
        "sinon": "^7.2.2",
        "snazzy": "^8.0.0",
        "standardx": "^3.0.1",
        "updates": "^6.0.3"
      },
      "engines": {
        "node": ">=11"
      },
      "homepage": "https://git.inc.sh/IdeasNeverCease/gotql",
      "husky": {
        "hooks": {
          "pre-commit": "npm run test:lint",
          "pre-push": "npm run format"
        }
      },
      "keywords": [
        "framework",
        "graph",
        "graphql",
        "post",
        "query",
        "server-side"
      ],
      "license": "MIT",
      "main": "index.js",
      "name": "@inc/gotql",
      "private": false,
      "repository": {
        "type": "git",
        "url": "https://git.inc.sh/IdeasNeverCease/gotql.git"
      },
      "scripts": {
        "format": "eslint '**/*.js' --fix",
        "test": "run-s test:*",
        "test:dependencies": "updates -u ./",
        "test:lint": "standardx --verbose | snazzy",
        "test:test": "ava --color -v -T 10000"
      },
      "version": "1.4.0",
      "gitHead": "32fa5c1e72e74c4779db7ff2409484fcae400532",
      "_id": "@inc/gotql@1.4.0",
      "_npmVersion": "6.5.0",
      "_nodeVersion": "11.4.0",
      "_npmUser": {
        "name": "netoperatorwibby",
        "email": "netopwibby@thenetwork.email"
      },
      "dist": {
        "integrity": "sha512-lTAVwM8rBkhShzrwSVSzlXEJ9PI0t0Cjje51WqNRxFVhFFZYByRn6MU/Fz4CJUunEQAc4hILRhNNBuiRi+257w==",
        "shasum": "a7bd0f9509038511875acf1be68e3a7bdd9d9498",
        "tarball": "https://npm.inc.sh/@inc%2fgotql/-/gotql-1.4.0.tgz",
        "fileCount": 10,
        "unpackedSize": 34315,
        "npm-signature": "-----BEGIN PGP SIGNATURE-----\r\nVersion: OpenPGP.js v3.0.4\r\nComment: https://openpgpjs.org\r\n\r\nwsFcBAEBCAAQBQJcNbBCCRA9TVsSAnZWagAAkwkP/i1VlKIg0ZyWIO0y//g6\neyiLrYxJee9IIN4MQ9BVit8MWuWdzGWXzkevPO4M7vW9UpmyKXhQ4lELWFdo\n+3qIplWsw2ar1iLYhGJsgRU847/DGIjrcLj4Lqr1QcSy7WJQzFyFRkiqyxLx\n3DFTKJo8UHbAD5yO/20UOF5Mz9LpKjK2jQV8apg5rnEITgXGTEkGROzcPvVT\nIvv8bXbtP836IKlz9R2njN2ZW9cJ/e1r1Md9RbXEPLtkmaF9oAjZJZ0dfI/q\nRy9SkSgMWE+q2mOCMMnZ9S1vHk+vniOzbWtnfljbHQ05niurd8kknFML9Dq9\na8JDVqJRWvJ3KlQke2U+kS2dMvYlZ5HT97TDXoC0lKIKucULbjm3QnumZySn\nEimtLOEh+x//1V3/acZntL2WekOir3fJWKbr/OFoBIBebti20uSh3yE6UQ63\n9a3KuX0x0tobNih7Y8m5I/i1ghTpcjX8EdbpFzpTVfWpzve68QSvjR18QBBM\nCe7urfl+M/61d2ZB6MqojswCYM38YoGytCYi311XhJ9TQrluXMSN0Jhw1NU/\nIHUfgX4F/s9PTTNQ3og/TFEA4dDFdzYouCRqfwEW31u6cKb0aZ0mhRisci/J\nVfa6LR7CoS5LCD3cVJ6KDFMHdFQJHapcZFTpPJxNG8bb5BCni77yNenSK/4c\nlg+/\r\n=U2vM\r\n-----END PGP SIGNATURE-----\r\n"
      },
      "maintainers": [
        {
          "name": "netoperatorwibby",
          "email": "netopwibby@thenetwork.email"
        }
      ],
      "directories": {},
      "_npmOperationalInternal": {
        "host": "s3://npm-registry-packages",
        "tmp": "tmp/gotql_1.4.0_1547022401911_0.2539772116282484"
      },
      "_hasShrinkwrap": false
    },
    "1.4.1": {
      "author": {
        "name": "Paul Anthony Webb",
        "email": "paul@inc.sh"
      },
      "bugs": {
        "url": "https://hub.socii.network/inc"
      },
      "dependencies": {
        "got": "^9.5.0",
        "prepend-http": "^2.0.0"
      },
      "description": "A GraphQL query framework for server-side apps",
      "devDependencies": {
        "@inc/eslint-config": "^1.1.2",
        "ava": "^1.0.1",
        "eslint": "^5.12.0",
        "husky": "^1.3.1",
        "npm-run-all": "^4.1.5",
        "sinon": "^7.2.2",
        "snazzy": "^8.0.0",
        "standardx": "^3.0.1",
        "updates": "^6.0.3"
      },
      "engines": {
        "node": ">=11"
      },
      "files": [
        "src",
        "index.js"
      ],
      "homepage": "https://git.inc.sh/IdeasNeverCease/gotql",
      "husky": {
        "hooks": {
          "pre-commit": "npm run test:lint",
          "pre-push": "npm run format"
        }
      },
      "keywords": [
        "framework",
        "graph",
        "graphql",
        "post",
        "query",
        "server-side"
      ],
      "license": "MIT",
      "main": "index.js",
      "name": "@inc/gotql",
      "private": false,
      "repository": {
        "type": "git",
        "url": "https://git.inc.sh/IdeasNeverCease/gotql.git"
      },
      "scripts": {
        "format": "eslint '**/*.js' --fix",
        "test": "run-s test:*",
        "test:dependencies": "updates -u ./",
        "test:lint": "standardx --verbose | snazzy",
        "test:test": "ava --color -v -T 10000"
      },
      "version": "1.4.1",
      "readmeFilename": "README.md",
      "gitHead": "4912b20972574d5bb6904826391978568d1151d0",
      "_id": "@inc/gotql@1.4.1",
      "_npmVersion": "6.5.0",
      "_nodeVersion": "11.4.0",
      "_npmUser": {},
      "dist": {
        "integrity": "sha512-DQkrPYtMTTvrOhVkVhQYKCF+qeEz5LhwYOrxtonb+BUAdkFyaEtjkbO52uiFSIvnL5lkK7+VnOEBpwlNahaZ4g==",
        "shasum": "e32f63ac2a96bea479b39c90fa767ea2ee9af07f",
        "tarball": "https://npm.inc.sh/@inc%2fgotql/-/gotql-1.4.1.tgz"
      }
    }
  },
  "time": {
    "created": "2019-01-09T08:26:41.794Z",
    "1.4.0": "2019-01-09T08:26:42.072Z",
    "modified": "2019-01-27T21:16:08.634Z",
    "1.4.1": "2019-01-27T21:16:08.634Z"
  },
  "dist-tags": {
    "latest": "1.4.1"
  },
  "_rev": "19-255e39c470ac6aec",
  "_id": "@inc/gotql",
  "readme": "# @inc/gotql\n\n> Write GraphQL queries as objects instead of strings\n\n*Forked from [khaosdoctor/gotql](https://github.com/khaosdoctor/gotql), I did not feel like waiting for [my PR](https://github.com/khaosdoctor/gotql/pull/5) to be accepted and I have things to do.*\n\n[![Vulnerabilities in this package](https://snyk.io/test/npm/@inc/gotql/badge.svg?style=flat-square)](https://snyk.io/test/npm/@inc/gotql)\n\n<!--/ Gitea does not display SVGs...STILL\n  ![GotQL logo](https://git.inc.sh/IdeasNeverCease/gotql/raw/branch/master/media/gotql.svg)\n/-->\n\n<br/>\n\nThis is a better implementation of the [GraphQL](https://github.com/facebook/graphql) query API via NodeJS, created as a wrapper of [Got](http://github.com/sindresorhus/got). It works like a transpiler, with a built in HTTPRequest Client (Got), allowing you to write your GraphQL queries as Javascript Objects instead of strings.\n\nBuilt because manipulating strings is a real pain.\n\n# Table of Contents\n\n<!-- TOC -->\n\n- [Table of Contents](#table-of-contents)\n  - [Install](#install)\n  - [Basic Usage](#basic-usage)\n  - [What is it?](#what-is-it)\n    - [Motivation](#motivation)\n  - [API](#api)\n    - [Returns](#returns)\n  - [The JSON query format](#the-json-query-format)\n    - [Description](#description)\n    - [Examples](#examples)\n      - [Simple query](#simple-query)\n      - [Named query](#named-query)\n      - [Query with simple args](#query-with-simple-args)\n      - [Query with variables](#query-with-variables)\n      - [Nested fields](#nested-fields)\n      - [Enum args](#enum-args)\n  - [Contributing to this project](#contributing-to-this-project)\n\n<!-- /TOC -->\n\n## Install\n\n```sh\n$ npm i @inc/gotql -S\n```\n\n## Basic Usage\n\n```js\nconst gotQl = require(\"gotql\")\n\nconst query = {\n  operation: {\n    name: \"users\",\n    fields: [\"name\", \"age\", \"id\"]\n  }\n}\n\nconst options = {\n  headers: {\n    \"Authorization\": \"Bearer <token>\"\n  },\n  debug: false\n}\n\ngotQL.query(\"mygraphqlendpoint.com.br/api\", query, options)\n  .then(response => console.log(response.data))\n  .catch(console.error)\n```\n\n## What is it?\n\nGotQL is a better interface for GraphQL queries. It provides a way for developers to run queries using JSON instead of strings. Which is a way more usable data format than the string itself.\n\n### Motivation\n\nManipulating strings is very smelly, even on dynamically typed languages. So, in order to avoid things such as this:\n\n![](./media/motivation-example.png)\n\nWhich can be translated to something waay more readable in a JSON format like this:\n\n```js\nconst mutation = {\n  operation {\n    name: \"addLog\",\n    args: {\n      logType: { value: \"status_change\", escape: false}, // Enum Value\n      fromState: variables.fromState,\n      toState: variables.toState,\n      idUser: variables.idUser,\n      idCampaign: variables.idCampaign,\n      owner: {\n        ownerType: variables.ownerType,\n        username: variables.username,\n        picture: variables.picture,\n        name: variables.name,\n        id: variables.id\n      }\n    },\n    fields: [ \"uuid\" ]\n  }\n}\n```\n\nThis is why GotQL was created.\n\n## API\n\n```js\ngotQl.query(graphQLEndpoint, query, [options])\n```\n\n- **Description**: Performs a graphQL query\n\n**GraphQLEndpoint**\n\n- Type: `string`\n- Description: The GraphQL endpoint to query on\n\n**query**\n\n- Type: `object`\n- Description: The JSON-typed query following the [json-query format](#the-json-query-format)\n\n**options**\n\n- Type: `object`\n- Description: The option object with the following properties.\n  - _debug_: Activates debug logging\n    - Type: `boolean`\n  - _errorStatusCode_: Default HTTP status code to be returned on error\n    - Type: `number`\n  - _headers_: Additional headers to be sent\n    - Type: `object`, in the form of `[headerName: string]: headerValue: string`\n\n---\n\n```js\ngotQl.mutation(graphQLEndpoint, query, [options])\n```\n\n- **Description**: Performs a graphQL mutation\n\n**GraphQLEndpoint**\n\n- Type: `string`\n- Description: The GraphQL endpoint to query on\n\n**query**\n\n- Type: `object`\n- Description: The JSON-typed query following the [json-query format](#the-json-query-format)\n\n**options**\n\n- Type: `object`\n- Description: The option object with the following properties.\n  - _debug_: Activates debug logging\n    - Type: `boolean`\n  - _errorStatusCode_: Default HTTP status code to be returned on error\n    - Type: `number`\n  - _headers_: Additional headers to be sent\n    - Type: `object`, in the form of `[headerName: string]: headerValue: string`\n\n---\n\n```js\ngotQl.parser(query, type)\n```\n\n- **Description**: Parses a JSON-Like query and returns the query\"s string\n\n**query**\n\n- Type: `object`\n- Description: The JSON-typed query following the [json-query format](#the-json-query-format)\n\n**type**\n\n- Type: `string`\n- Description: Must be either `\"query\"` or `\"mutation\"`\n\n### Returns\n\nAll methods return a `string` like this:\n\n```js\nconst response = \"query { test { name args } }\"\n```\n\n## The JSON query format\n\nThe JSON format gotQL uses is a simple and intuitive description based on the [anatomy of a GraphQL query](https://dev-blog.apollodata.com/the-anatomy-of-a-graphql-query-6dffa9e9e747) blog post.\n\nThis is a generic model of a JSONLike query:\n\n```js\nconst query = {\n    name?: string;\n    operation: {\n        name: string;\n        alias?: string;\n        args?: {\n            [argName: string]: any;\n        } | {\n          [argName: string]: {\n              value: string;\n              escape: boolean;\n          };\n        };\n        fields: (string | {\n            [fieldName: string]: [{\n                fields?: (string | {\n                    [fieldName: string]: [any];\n                })[];\n            }];\n        })[];\n    };\n    variables?: {\n        [varName: string]: {\n            type: string;\n            value: string;\n        };\n    };\n}\n```\n\n### Description\n\n- Query:\n  - Type: `object`\n  - Description: The full query object\n  - Properties:\n    - _name_: [optional]: Query name\n      - Type: `string`\n    - _variables_: [optional] Query variable declaration\n      - Type: `object` with signature like `[varName: string]: { type: string, value: string }`\n      - Properties:\n        - _varName_: Variable name\n          - Type: `string`\n        - _type_: Variable type. Can be a GraphQL definition of type (i.e: `string!`)\n          - Type: `string`\n        - _value_: Variable value\n          - Type: `any`\n    - _operation_: The query operation (action that will be executed)\n      - Type: `object`\n      - Properties:\n        - _name_: The operation name\n          - Type: `string`\n        - _alias_: [optional] An alias to give the operation\n          - Type: `string`\n        - _args_: [optional] The operation args\n          - Type: `[argName: string]: any` or a detailed arg object\n            - **_Simple args_**: An `object` where the key is the argument name and its value. Accepts variables in the format of `argName: \"$value\"`\n              - Example: `args { name: \"myName\" }`\n            - **_Detailed args_**: An object with two properties. This will give more control over escaping (mostly to use enums). Argument name should be the key\n              - Type: `object`\n              - Properties:\n                - _value_: The argument value\n                  - Type: `any`\n                - _escape_: Whether the argument should be escaped or not (escaped means surrounded with double quotes `\"argValue\"`)\n                  - Type: `boolean`\n              - Examples: `args: { status: { value: \"an_enum\", escape: false } }` should output `operation (status: an_enum)...`\n        - _fields_: The field list to get back from the operation\n          - Type: An `array` of `object` (to use nested fields) or `string`, or both.\n          - Properties (for nested fields):\n            - Type: `object` where the field name is the key\n            - _fields_: Recursive definition, accepts another array just like the _field* 113 data bytes written
s_ above.\n\n### Examples\n\n#### Simple query\n\n```js\nconst query = {\n  operation: {\n    name: \"users\",\n    fields: [\"name\", \"age\"]\n  }\n}\n```\n\nOutputs:\n\n```js\nquery { users { name age }}\n```\n\n#### Named query\n\n```js\nconst query = {\n  name: \"myQuery\",\n  operation: {\n    name: \"users\",\n    fields: [\"name\", \"age\"]\n  }\n}\n```\n\nOutputs:\n\n```js\nquery myQuery { users { name age }}\n```\n\n#### Query with simple args\n\n```js\nconst query = {\n  operation: {\n    name: \"user\",\n    args: {\n      name: \"T'Challa\"\n    }\n    fields: [\"name\", \"age\"]\n  }\n}\n```\n\nOutputs:\n\n```js\nquery { user(name: \"T'Challa\") { name age }}\n```\n\n#### Query with variables\n\n```js\nconst query = {\n  variables: {\n    name: {\n      type: \"string!\",\n      value: \"T'Challa\"\n    }\n  },\n  operation: {\n    name: \"user\",\n    args: {\n      name: \"$name\"\n    }\n    fields: [\"name\", \"age\"]\n  }\n}\n```\n\nOutputs:\n\n```js\nquery ($name: string!) { users(name: $name) { name age }}\n```\n\nVariables are sent on a separate object to graphQL.\n\n```json\n{\n  \"variables\": { \"name\": \"T'Challa\" }\n}\n```\n\n#### Nested fields\n\n```js\nconst query = {\n  operation: {\n    name: \"users\",\n    fields: [\"name\", \"age\", { friends: { fields: [\"name\", \"age\"] }}]\n  }\n}\n```\n\nOutputs:\n\n```js\nquery { users { name age friends { name age }}}\n```\n\nRecursive fields can go forever.\n\n#### Enum args\n\n```js\nconst query = {\n  operation: {\n    name: \"user\",\n    args: {\n      type: {\n        value: \"internal\",\n        escape: false\n      }\n    }\n    fields: [\"name\", \"age\"]\n  }\n}\n```\n\nOutputs:\n\n```js\nquery { users(type: internal) { name age }}\n```\n\nIf `escape` is set to `true`, the output would be:\n\n```js\nquery { users(type: \"internal\") { name age }}\n```\n\n> **Note:** Variables such as described [here](#query-with-variables) _will **not**_ be recognized. If the arg object is not an `[argName]: value`, variables will not pass through the definition check (GotQL warns if a variable is not declared but used on operation).",
  "_attachments": {}
}
```

**Comment by silverwind** [comment]
Okay so we need to find out which packages are pulled from `npm.inc.sh` and which from `registry.npmjs.org`. I'm sorry, I have never worked with private packages. How do you specify where to pull which package. Or does npm find that out automatically based on some data in their registry?

**Comment by silverwind** [comment]
One guess on how it might work: First npm tries to retrieve the package from the private registry, if it gets a 404 there, it then pulls the package from registry.npmjs.org. That would explain your 404.

So I think I need to implement https://github.com/silverwind/updates/issues/20 and then implement the fallback on 404.

**Comment by silverwind** [comment]
Try 7.1.0, it might just work.

**Comment by NetOperatorWibby** [comment]
It _does_! Thank you @silverwind!
