### ISSUE TITLE
updates seems to ignore "strict-ssl=false" npm setting

### ISSUE THREAD

**Issue by fidgi** [silverwind/updates#55]
Hi,
I've a configuration where I need to fetch npm packages from a private mirror in Nexus w/ self-signed CA certificates .
I've run "npm config set strict-ssl false" but still get the following error : 

`npx updates
npx : 1 installé(s) en 5.671s
FetchError: request to https://nexus.****.fr/repository/npm-npmjs-proxy/commander failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (/home/****/.npm/_npx/15590/lib/node_modules/updates/updates.cjs:54:31315)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:327:22)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)`

Same error if I install updates globally w/ "npm -g i updates"

npm -v
6.14.12
node -v
v14.16.1
uname -a
Linux debian-dev 4.9.0-15-amd64 #1 SMP Debian 4.9.258-1 (2021-03-08) x86_64 GNU/Linux

Regards,
PS: thx for sharing this tool

**Comment by silverwind** [comment]
Hmm yes that seems like a bug, should be easy enough to fix.

**Comment by silverwind** [comment]
Try again with 12.1.0.

**Comment by fidgi** [comment]
It works fine . thanks.
